name: Convert Resume to PDF and HTML

on:
  push:
    paths:
      - 'resume.md'
      - '.github/workflows/convert-resume.yml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  convert_resume:
    name: Convert Resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Convert to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: resume.md
          output_dir: /      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'          
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc
      - name: Convert Markdown files to Word
        run: |
          # for file in $(find . -name "*.md"); do
          #   # Skip README.md
          #   if [ "$(basename $file)" = "README.md" ]; then
          #     continue
          #   fi
            
          #   # Create output filename
          #   outfile="${file%.md}.docx"
            
            echo "Converting $file to $outfile"
            pandoc "resume.md" \
              -f markdown \
              -t docx \
              -o "resume.docx" \
              --standalone 
              # \
              # --reference-doc=template.docx || true
          # done
                    
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions [bot]"
          git add resume.pdf resume.html resume.docx
          git commit -m "Update resume PDF and HTML" || echo "No changes to commit"
          git push
